### ISSUE TITLE
Keyboard requires root

### ISSUE THREAD

**Issue by OctoRocket** [azh412/VirtualPianoBot#3]
The keyboard library fails as it needs to be root.

Traceback (most recent call last):
  File "/tmp/VirtualPianoBot/VirtualPianoBot.py", line 41, in <module>
    if keyboard.is_pressed("]"):
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 410, in is_pressed
    _listener.start_if_necessary()
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/octorocket/.local/lib/python3.10/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.

This is an issue as you can't just run it as root as the root user needs to have the pip packages installed.

**Comment by OctoRocket** [comment]
also why are you importing random if you aren't using it?

**Comment by OctoRocket** [comment]
ded
